rplidarNode:
  ros__parameters:
    serial_port: /dev/rplidar
    serial_baudrate: 256000
    frame_id: lidar_link
    inverted: false
    angle_compensate: true

bno055_driver:
  ros__parameters:
    port: /dev/ttyUSB2
    frame_id: imu_link
    frequency: 30.0
    self_manage: true
    use_magnetometer: true

    angular_velocity_stdev: 0.01
    linear_acceleration_stdev: 0.0015
    magnetic_field_stdev: 0.0000005
    orientation_stdev: 0.000001
    # these calibration values need to be determined on a per-device basis.
    calibration/accelerometer_offset: [-7, -34, -47]
    calibration/magnetometer_offset: [275, -193, -104]
    calibration/gyroscope_offset: [-3, -3, -1]
    calibration/accelerometer_radius: 1000
    calibration/magnetometer_radius: 842